# Site settings
title: 数据科学沉思录
header-img: "img/meditations_1.jpg"
tagline: "cn"  
description: "黄耀鹏|技术分享.思想结晶"  
baseurl: ""
url: "http://yphuang.github.io"  

# About/contact
owner: 
  name: " yphuang"
  email: "huangypatgx@gmail.com"
  bio: ""
  
author:
  name: 黄耀鹏      # 作者名称
  email: huangypatgx@gmail.com # 邮箱地址
    #weibo: 2917650677  # weibo ID
  github: brightbird  # github ID
    #linkedin: chrispher-guan/5a/a68/6b8 # linkedIn ID
    #gplus: 110552447039675960964  # G+ ID 
  logo: https://github.com/yphuang/yphuang.github.io/blob/master/img/favicon.ico.png # logo地址

# Data
gavatar: http://dreamofbook.qiniudn.com/Az..png
favicon: img/favicon.png

douban_username:  
#twitter_username: 
github_username: brightbird
#facebook_username: 
#weibo_username: 
zhihu_username: brightbirdhuang

# Build settings  
# use Github Flavored Markdown !important  
# document: http://jekyllrb.com/docs/configuration/#kramdown  
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 8
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: Asia/Beijing

# Defaults for posts
defaults:
  -
    scope: 
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "yphuang"
      header-img: "img/green.jpg" # We don't want posts without a header image, that whould mean white on white

# Comments 
comments :
  provider : duoshuo
  duoshuo :
    short_name : yphuang
  disqus :
      short_name : yphuang

# Analytics and webmaster tools stuff goes here
google_analytics: 
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in footer navigation
footer-links-active:
  rss: true
  zhihu: true
  facebook: false
  email: true
  twitter: false
  github: true
  linkedin: false
  stackoverflow: false

#   
url-pretty: "huangypatgx@gmail.com"
